spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:shop_toy
    username: sa
    password: sa
  h2:
    console:
      enabled: true
      path: /h2
#    driver-class-name: org.postgresql.Driver
#    url: jdbc:postgresql://localhost:5432/shop_toy
#    username: postgres
#    password: postgresql
  liquibase:
    change-log: classpath:/changelog/master.xml
  jpa:
    hibernate:
      ddl-auto: none
      database-platform: org.hibernate.dialect.H2Dialect
#      database-platform: org.hibernate.dialect.PostgreSQL10Dialect
      show-sql: true
jwt:
  header: Authorization
  secret: secret
  experation: 604800