spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/shop_toy
    username: postgres
    password: postgresql
  liquibase:
    change-log: classpath:/changelog/master.xml
  jpa:
    hibernate:
      ddl-auto: none
      database-platform: org.hibernate.dialect.PostgreSQL10Dialect
      show-sql: true